/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Juego.ControlFiguras;
import Juego.ControlJugadores;
import Juego.Tablero;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Shape;
import javax.swing.JButton;

/**
 *
 * @author Daniel Rojas
 */
public class PnlTablero extends javax.swing.JPanel {

    Image fondo;
    ControlJugadores jugadores;
    private JButton botonesHorizontales[][];
    private JButton botonesVerticales[][];
    Tablero tablero;

    /**
     * Creates new form Tablero
     */
    public PnlTablero(ControlJugadores jugadores) {
        initComponents();
        
        this.jugadores = jugadores;
        tablero = new Tablero();
        ControlFiguras cfiguras = new ControlFiguras();
   
        if (jugadores.cantidadJugadores() == 2) {
            tablero.crearTablero(10);
        } else if (jugadores.cantidadJugadores() == 3) {
            tablero.crearTablero(20);
        } else {
            tablero.crearTablero(40);
        }
        
        botonesHorizontales = tablero.getBotonesHorizontales();
        botonesVerticales = tablero.getBotonesVerticales();
        
        
    }

    
    
    /**
     * Método para pintar cuadros y líneas en el tablero
     * @param grphcs 
     */
    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        
        
//        Graphics2D g2 = (Graphics2D) grphcs.create();
//        for (Shape figura : figuras) {
//            g2.draw(figura);
//        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
